Deprecating all `::fromArray()` methods in in the package
laminas/laminas-code pull request #153
Opened 2022-11-18 13:52 UTC by Ocramius

|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

Deprecating all `::fromArray()` methods in in the package

These methods are brittle, badly documented, and very much
type-unsafe.

The `src/Generator` API is mostly composed of builder objects,
and `::fromArray()` is not necessary in it.

Please also do not use arbitrary user input, deserialized as
array, to generate code: it's a recipe for disaster.

2022-11-18 14:02 UTC, froschdesign requested changes
Good decision. The configuration arrays are ugly to use and difficult to document.

Only one small suggestion.

2022-11-18 14:02 UTC, froschdesign commented on docs/book/generator/examples.md
> +    ->generate();
This looks much cleaner and at the same time the code completion works. 👍🏻

2022-11-18 14:02 UTC, froschdesign commented on docs/book/generator/examples.md
> +    ->setBody('define(\'APPLICATION_ENV\', \'testing\');');
```suggestion
    ->setBody("define('APPLICATION_ENV', 'testing');");
```

2022-11-18 14:15 UTC, merged

2023-08-22 08:30 UTC, tyteen4a03 commented
Hi, will https://docs.laminas.dev/laminas-code/generator/examples/ be updated?

2023-08-22 12:05 UTC, Ocramius commented
@tyteen4a03 by someone, yes: are you volunteering? 😁

2023-08-22 12:10 UTC, tyteen4a03 commented
@mtorromeo I'm not sure what is needed from me because it looks like the docs in the repo are updated but the website doesn't render the latest version of the docs.

2023-08-22 12:12 UTC, Ocramius commented
@tyteen4a03 aha! Thanks for checking: that's indeed for us to find out then /cc @froschdesign

2023-08-22 12:45 UTC, froschdesign commented
The problem is the build process for the documentation: https://github.com/laminas/laminas-code/actions/workflows/docs-build.yml - but the logs are gone.

2023-08-24 07:48 UTC, froschdesign commented
@tyteen4a03 
The problem is solved: https://docs.laminas.dev/laminas-code/generator/examples/#generating-php-classes

Thanks to @Xerkus