Correction of Laminas\Code\Generator\DocBlock\Tag\ParamTag example
laminas/laminas-code pull request #65
Opened 2020-12-11 13:19 UTC by mdthh

1st Parameter for Laminas\Code\Generator\DocBlock\Tag\ParamTag::_construct() does not accept an array. Also: Adding example that parameter 'types" may also be array (e.g. 'string' and 'array') and contain a description.
* Documentation improvement: master branch

|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | yes
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description
There's an error in the given example: The constructor for Laminas\Code\Generator\DocBlock\Tag\ParamTag is not a single array. Also extended the example by using an array for parameter 'types' and adding the 'description' parameter.

2020-12-11 13:23 UTC, Ocramius requested changes

2020-12-11 13:23 UTC, Ocramius commented on docs/book/generator/examples.md
> +                        )
`),` (comma needed here), and need to fix some alignment

2020-12-11 16:07 UTC, mdthh commented
I use Git & Github very rarely. Could you kindly hint me on how to proceed with implementing your corrections on my fork so it meets your requirements .

2021-03-27 13:46 UTC, Ocramius commented
@mdthh sorry, totally missed to follow up here: I'll get your branch fixed and merged locally :-)

For future reference, when/if it comes up, you can clone your fork to any local directory, edit the files on the branch you were working on, then push that branch, and the pull request will be updated implicitly.

2021-03-27 13:52 UTC, closed without merging

2021-03-27 13:52 UTC, Ocramius commented
Rebased and merged manually, thanks @mdthh!